[mypy]
exclude = venv/

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-canvasapi.*]
ignore_missing_imports = True

[mypy-jmespath.*]
ignore_missing_imports = True

[mypy-guardrails.*]
ignore_missing_imports = True

[mypy-data_access.individual_quest_dao]
ignore_missing_imports = True

[mypy-tests.*]
ignore_errors = True
