# Development Environment Variables
variables:
  environment: 'dev'
  awsRegion: 'us-east-2'
  apiGatewayStackName: 'eduquest-api-dev'
  deploymentBucket: 'eduquest-deployments-dev'
  stageName: 'dev'
  ec2InstanceId: 'i-02c46d8036081b9df'
  ec2PublicIp: '3.15.42.96'
