# Production Environment Variables
variables:
  environment: 'prod'
  awsRegion: 'us-east-2'
  apiGatewayStackName: 'eduquest-api-prod'
  deploymentBucket: 'eduquest-deployments-prod'
  stageName: 'prod'
  ec2InstanceId: 'i-0c92bee4d75c4ff48'
  ec2PublicIp: '18.117.155.99'
