"""
Public demo endpoint — no auth required.

POST /demo/quest accepts a grade level and interests, returns a long-term
goal and four weekly quests generated by DemoLTGAgent. Used by the landing
page to let visitors preview AI-generated content before signing up.
"""
from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from routers.deps import get_bot_provider
from services.demo.demo_ltg_service import DemoLTGService

router = APIRouter()


class DemoQuestRequest(BaseModel):
    grade: str = Field(..., description="Grade level, e.g. 'k', '1', '6', '12'")
    subject: str = Field(..., description="Subject, e.g. 'Math', 'Science'")
    interests: list[str] = Field(..., min_length=1, max_length=3, description="1–3 child interests")


@router.post("/quest")
async def generate_demo_quest(
    body: DemoQuestRequest,
    bot_provider=Depends(get_bot_provider),
):
    svc = DemoLTGService(bot_provider=bot_provider)
    return await svc.generate(body.grade, body.interests, body.subject)
